# Generated by Django 4.2 on 2026-05-05 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='close_reason',
            field=models.CharField(blank=True, choices=[('work_done', 'Work Done'), ('found_workers', 'Found Workers'), ('postponed', 'Postponed'), ('other', 'Other')], max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='close_remark',
            field=models.TextField(blank=True),
        ),
    ]
