# Generated by Django 4.2 on 2026-05-05 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicelisting',
            name='coverage_km',
            field=models.IntegerField(choices=[(10, '10 km'), (25, '25 km'), (50, '50 km'), (100, '100 km')], default=50),
        ),
    ]
