# Generated by Django 4.2 on 2026-05-05 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('farmer', 'Farmer'), ('labour', 'Labour'), ('provider', 'Provider'), ('admin', 'Admin')], max_length=20),
        ),
    ]
