# Generated by Django 4.2 on 2026-05-05 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_district_alter_user_village'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_ready_for_work',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ready_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
